Csl 2059 net sdk add support for quizzes api
Constructor-io/constructorio-netcore pull request #32
Opened 2023-02-21 15:44 UTC by mocca102

2023-02-24 19:29 UTC, stanlp1 requested changes
Small comments. Otherwise it looks good to me.

2023-02-24 19:29 UTC, stanlp1 commented on src/constructor.io/models/Quizzes/QuizRequest.cs
> +        public Dictionary<string, string> TestCells { get; set; }
Not sure if we should include section/test cells here.

For section, I don't think there's currently a way to create quizzes for other sections.

For test cells, I don't think the api actually does anything with it.

2023-02-24 19:30 UTC, stanlp1 commented on src/Constructorio_NET.Tests/client/modules/QuizzesTests.cs
> +    public class QuizzesTest
Can we add a test that checks if all the attributes in a quiz question are there, correct? Like the description, id, title, images...

That way we can be sure that the attributes deserialized correctly.

2023-03-06 22:47 UTC, stanlp1 approved these changes
LGTM.

2023-03-06 22:47 UTC, stanlp1 commented on src/constructor.io/utils/Helpers.cs
> +                if (queryParams.Contains(Constants.ANSWERS))
Nice catch, missed this one.

Looking good to me. Lets have someone else have a final pass.

2023-03-07 19:28 UTC, Mudaafi commented on src/constructor.io/models/Quizzes/QuestionOption.cs
> +    }
I believe the `multiple` and `single` question types have an [image property in options](https://docs.constructor.io/rest_api/quiz/using_quizzes/#multiple-select).

2023-03-13 15:17 UTC, Mudaafi approved these changes
LGTM! Thanks for making the changes <3

2023-03-23 20:38 UTC, merged